name: CI CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn test --file demo/pom.xml
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-node@v6.4.0
      with:
        node-version: '24'
        cache: npm
        cache-dependency-path: note/package-lock.json
    - name: Build 
      run: npm ci
      working-directory: note
    - name : Run tests
      run: npm run test
      working-directory: note
